module.exports = ASPECTS = [
  'team efficiency',
  'project outcomes',
  'customer engagement',
  'operational effectiveness',
  'product quality',
  'financial stability',
  'innovation capacity',
  'brand reputation',
  'market adaptability',
  'internal processes',
  'employee satisfaction',
  'risk management',
  'supply chain resilience',
  'customer satisfaction',
  'revenue growth',
  'cost efficiency',
  'time-to-market',
  'compliance adherence',
  'technological advancement',
  'sustainability practices',
  'user experience',
  'stakeholder trust',
  'competitive advantage',
  'data-driven decision making',
  'corporate governance',
  'environmental impact',
  'social responsibility',
  'customer retention',
  'scalability',
  'cultural alignment',
];
