module.exports = ASPECTS = [
  'decentralization of power',
  'network security',
  'transaction transparency',
  'community engagement',
  'scalability solutions',
  'developer collaboration',
  'user adoption',
  'protocol robustness',
  'financial inclusivity',
  'innovation in payment systems',
  'public perception',
  'regulatory compliance',
  'transaction speed',
  'cost of transactions',
  'market liquidity',
  'sustainability of mining practices',
  'digital asset reputation',
  'resilience to censorship',
  'ease of access',
  'impact on financial systems',
  'user empowerment',
  'ecosystem partnerships',
  'open-source development',
  'technological evolution',
  'global reach',
  'security protocols',
  'privacy measures',
  'long-term viability',
  'volatility management',
  'community trust',
  'interoperability with other blockchains',
  'educational outreach',
  'market integration',
  'ecosystem support',
  'trading platform effectiveness',
  'transaction verification',
  'social impact of Bitcoin',
  'user experience design',
  'governance model effectiveness',
  'brand recognition',
  'diversity in the developer community',
  'adoption by institutions',
  'long-term investment perspective',
  'impact on remittances',
  'strategic partnerships with exchanges',
  'international regulation response',
  'influence on other cryptocurrencies',
  'impact on emerging markets',
];
