module.exports = ISSUES = [
  'technical challenges in blockchain implementation',
  'resource constraints for mining operations',
  'communication breakdowns within the crypto community',
  'limited access to reliable market data',
  'budget overruns in development projects',
  'high staff turnover in crypto startups',
  'inconsistent results from mining operations',
  'poor system integration with traditional finance',
  'regulatory hurdles in various jurisdictions',
  'project delays due to network congestion',
  'scope creep in crypto development projects',
  'data breaches affecting user wallets',
  'lack of stakeholder alignment in governance',
  'inadequate training on blockchain technology',
  'technology obsolescence of mining hardware',
  'poor project management in crypto ventures',
  'unexpected downtime during network upgrades',
  'integration failures with payment systems',
  'performance bottlenecks during high transaction volumes',
  'security vulnerabilities in smart contracts',
  'incomplete requirements for new features',
  'user adoption issues among non-technical users',
  'conflicting priorities between stakeholders',
  'vendor reliability of crypto service providers',
  'insufficient testing of decentralized applications',
  'change resistance in traditional finance institutions',
  'workflow inefficiencies in crypto projects',
  'inadequate support for users',
  'quality assurance failures in blockchain products',
  'data migration issues between wallets',
  'knowledge gaps in blockchain technology',
  'automation challenges in trading bots',
  'inadequate infrastructure for scaling solutions',
  'project scope limitations in crypto startups',
  'interdepartmental conflicts in crypto organizations',
  'high turnover rates in development teams',
  'inaccurate forecasting of market trends',
  'technology gaps in blockchain solutions',
  'budget constraints in startup funding',
  'cultural resistance to decentralized finance',
  'lack of innovation in blockchain applications',
  'misaligned objectives among developers',
  'slow decision-making in governance structures',
  'inconsistent leadership in crypto projects',
  'customer dissatisfaction with exchange services',
  'insufficient resources for community outreach',
  'market volatility affecting investments',
  'legal complications in regulatory compliance',
  'inconsistent standards for blockchain protocols',
  'lack of contingency planning for network failures',
  'unclear accountability in decentralized governance',
];
