module.exports = ISSUES = [
  'technical challenges',
  'resource constraints',
  'communication breakdowns',
  'limited access to data',
  'budget overruns',
  'staff turnover',
  'inconsistent results',
  'poor system integration',
  'regulatory hurdles',
  'project delays',
  'scope creep',
  'data breaches',
  'lack of stakeholder alignment',
  'inadequate training',
  'technology obsolescence',
  'poor project management',
  'unexpected downtime',
  'integration failures',
  'performance bottlenecks',
  'security vulnerabilities',
  'incomplete requirements',
  'user adoption issues',
  'conflicting priorities',
  'vendor reliability',
  'insufficient testing',
  'change resistance',
  'workflow inefficiencies',
  'inadequate support',
  'quality assurance failures',
  'data migration issues',
  'knowledge gaps',
  'automation challenges',
  'inadequate infrastructure',
  'project scope limitations',
  'interdepartmental conflicts',
  'high turnover rates',
  'inaccurate forecasting',
  'technology gaps',
  'budget constraints',
];
