module.exports = JOBS = [
  'Blockchain Developer',
  'Cryptocurrency Analyst',
  'Bitcoin Core Developer',
  'Smart Contract Developer',
  'Crypto Compliance Officer',
  'Decentralized Finance (DeFi) Specialist',
  'Blockchain Architect',
  'Data Scientist in Crypto',
  'Security Auditor',
  'Cryptography Engineer',
  'Blockchain Consultant',
  'Bitcoin Market Analyst',
  'Crypto Community Manager',
  'Tokenomics Analyst',
  'Blockchain Product Manager',
  'Cryptocurrency Trader',
  'Digital Asset Manager',
  'Blockchain UX/UI Designer',
  'Crypto Project Manager',
  'Regulatory Affairs Specialist',
  'Blockchain Research Scientist',
  'Technical Writer for Crypto',
  'DevOps Engineer for Blockchain',
  'Smart Contract Auditor',
  'Blockchain Infrastructure Engineer',
  'Cryptocurrency Marketing Strategist',
  'Crypto Exchange Operator',
  'Bitcoin Mining Engineer',
  'Token Sale Manager',
  'Cryptocurrency Payment Specialist',
  'Blockchain Integration Specialist',
  'Data Privacy Officer in Blockchain',
  'Risk Management Analyst for Crypto',
  'Cryptocurrency Educator',
  'Blockchain Sales Engineer',
  'User Experience Researcher for Crypto',
  'Blockchain Operations Manager',
  'Technical Support Engineer for Crypto',
  'Blockchain Data Engineer',
  'Crypto Product Owner',
  'Digital Currency Specialist',
  'Blockchain Project Coordinator',
  'Decentralized Application (DApp) Developer',
  'Cryptocurrency Investment Analyst',
  'Bitcoin Wallet Developer',
  'Blockchain System Administrator',
  'Crypto Business Development Manager',
  'Cryptocurrency Risk Analyst',
  'Blockchain Innovation Specialist',
  'Chief Blockchain Officer',
  'Chief Cryptocurrency Officer',
  'Digital Currency Compliance Analyst',
  'Blockchain Security Specialist',
  'Financial Analyst for Digital Assets',
  'Bitcoin Payment Solutions Architect',
  'Crypto UX Researcher',
  'Blockchain Training Specialist',
  'Blockchain Governance Advisor',
  'Cryptocurrency Social Media Manager',
  'Bitcoin Ecosystem Strategist',
  'Smart Contract Product Manager',
  'Blockchain Community Outreach Coordinator',
  'Blockchain Development Manager',
  'Crypto Portfolio Manager',
  'Bitcoin Technology Evangelist',
  'Cryptocurrency Operations Analyst',
  'Blockchain Quality Assurance Engineer',
  'Cryptocurrency Product Marketing Manager',
  'Blockchain Analytics Specialist',
  'Regulatory Compliance Consultant',
  'Decentralized Identity Developer',
  'Blockchain Business Analyst',
  'Cryptocurrency Ecosystem Developer',
  'Token Governance Manager',
  'Blockchain Outreach Specialist',
  'Crypto Payment Gateway Developer',
  'Blockchain Technical Sales Consultant',
  'Cryptocurrency Event Coordinator',
  'Bitcoin Network Engineer',
  'Blockchain Data Scientist',
  'Crypto Supply Chain Analyst',
  'Cryptocurrency Brand Strategist',
  'Blockchain Investor Relations Manager',
  'Crypto Financial Advisor',
  'Blockchain Cloud Solutions Architect',
  'Blockchain DevSecOps Engineer',
  'Digital Asset Compliance Officer',
  'Blockchain Business Development Executive',
  'Blockchain Regulatory Analyst',
  'Crypto Market Research Analyst',
  'Decentralized Finance (DeFi) Product Manager',
];
