module.exports = JOBS = [
  'Data Scientist',
  'Blockchain Developer',
  'AI Researcher',
  'Cybersecurity Analyst',
  'Cloud Engineer',
  'Product Manager',
  'Business Analyst',
  'Software Engineer',
  'UX/UI Designer',
  'Systems Architect',
  'Digital Marketer',
  'Project Manager',
  'Operations Manager',
  'Financial Analyst',
  'Tech Lead',
  'Consultant',
  'Strategy Advisor',
  'Innovation Specialist',
  'Research Scientist',
  'Technical Writer',
  'DevOps Engineer',
  'Systems Administrator',
  'Product Designer',
  'Technical Project Manager',
  'Data Engineer',
  'Growth Hacker',
  'Customer Success Manager',
  'Compliance Officer',
  'Ethical Hacker',
  'Sales Engineer',
  'Artificial Intelligence Engineer',
  'Machine Learning Engineer',
  'Big Data Engineer',
  'Data Privacy Officer',
  'Risk Analyst',
  'Business Development Manager',
  'Marketing Strategist',
  'CRM Specialist',
  'Healthcare IT Specialist',
  'E-commerce Specialist',
  'Augmented Reality Developer',
  'Virtual Reality Developer',
  'Network Engineer',
  'Database Administrator',
  'Enterprise Architect',
  'Mobile App Developer',
  'IT Support Specialist',
  'Systems Engineer',
  'SAP Consultant',
  'Web Developer',
  'Content Strategist',
  'Product Owner',
  'Technical Support Engineer',
  'Data Visualization Specialist',
  'Software Architect',
  'Information Security Manager',
  'Automation Engineer',
  'IT Project Manager',
  'Cloud Solutions Architect',
  'Ethics Compliance Specialist',
  'Digital Transformation Specialist',
  'IoT Engineer',
  'Robotic Process Automation Developer',
  'AI Product Manager',
  'Cyber Intelligence Analyst',
  'Blockchain Architect',
  'Cloud Security Specialist',
  'Data Analytics Consultant',
  'Full Stack Developer',
  'Business Intelligence Analyst',
  'Network Security Engineer',
  'Tech Operations Manager',
  'Digital Experience Designer',
  'Machine Learning Researcher',
  'Data Engineering Manager',
  'Software Development Manager',
  'Health Informatics Specialist',
  'Technology Integration Specialist',
  'Chief Technology Officer',
  'Chief Information Security Officer',
  'User Researcher',
  'Automation Solutions Architect',
  'Digital Solutions Architect',
  'AI Ethics Officer',
  'Tech Innovation Manager',
];
