module.exports = PROBLEMS = [
  'inefficiencies',
  'bottlenecks',
  'resource gaps',
  'inadequate tools',
  'slow response times',
  'data inaccuracies',
  'communication issues',
  'lack of alignment',
  'scalability challenges',
  'integration difficulties',
  'high operational costs',
  'low productivity',
  'security vulnerabilities',
  'obsolete technology',
  'limited flexibility',
  'poor user experience',
  'inconsistent quality',
  'regulatory compliance issues',
  'unreliable data sources',
  'manual errors',
  'technical debt',
  'underutilized resources',
  'fragmented systems',
  'long implementation times',
];
