module.exports = PROBLEMS = [
  'scalability issues in the Bitcoin network',
  'high transaction fees during peak times',
  'security vulnerabilities in wallet software',
  'lack of regulatory clarity for cryptocurrency',
  'limited access to Bitcoin for unbanked populations',
  'inefficient mining practices leading to environmental concerns',
  'slow confirmation times for transactions',
  'fragmented exchange ecosystems',
  'communication barriers among Bitcoin users',
  'data integrity challenges in blockchain records',
  'low public understanding of Bitcoin technology',
  'inconsistent wallet security standards',
  'poor user experience in crypto trading platforms',
  'lack of interoperability between different blockchains',
  'high volatility affecting Bitcoin investments',
  'technical complexities in using Bitcoin',
  'insufficient customer support in crypto services',
  'limited integration of Bitcoin with traditional finance',
  'resistance to adopting Bitcoin from established institutions',
  'issues with Bitcoin forks and community disputes',
  'limited availability of Bitcoin ATMs',
  'problems with transaction privacy and anonymity',
  'data breaches in cryptocurrency exchanges',
  'lack of user-friendly interfaces in wallet applications',
  'issues with regulatory compliance for crypto businesses',
  'disparities in transaction speeds across different exchanges',
  'concerns about the long-term viability of Bitcoin mining',
  'inequities in access to crypto investment opportunities',
  'fragmented liquidity across various trading platforms',
  'challenges in recovering lost or stolen Bitcoin',
  'public relations challenges for cryptocurrency companies',
  'difficulties in maintaining transparency in crypto projects',
  'problems with smart contract vulnerabilities',
  'lack of standardization in crypto protocols',
  'user misconceptions about cryptocurrency risks',
  'over-reliance on centralized exchanges for trading',
  'difficulty in accurately forecasting market trends',
  'inefficient processes for onboarding new users',
  'problems with cross-border transactions in crypto',
  'limited understanding of tokenomics among users',
  'issues with network congestion during high demand',
  'lack of clarity on tax implications for crypto investors',
  'social engineering attacks targeting crypto users',
  'challenges in educating stakeholders on blockchain technology',
  'conflicts of interest among crypto project teams',
];
