module.exports = PROBLEMS = [
  'scalability issues in the Bitcoin network',
  'high transaction fees during peak times',
  'security vulnerabilities in wallet software',
  'lack of regulatory clarity for cryptocurrency',
  'limited access to Bitcoin for unbanked populations',
  'inefficient mining practices leading to environmental concerns',
  'slow confirmation times for transactions',
  'fragmented exchange ecosystems',
  'communication barriers among Bitcoin users',
  'data integrity challenges in blockchain records',
  'low public understanding of Bitcoin technology',
  'inconsistent wallet security standards',
  'poor user experience in crypto trading platforms',
  'lack of interoperability between different blockchains',
  'high volatility affecting Bitcoin investments',
  'technical complexities in using Bitcoin',
  'insufficient customer support in crypto services',
  'limited integration of Bitcoin with traditional finance',
  'resistance to adopting Bitcoin from established institutions',
  'issues with Bitcoin forks and community disputes',
];
