module.exports = TOPICS = [
  'AI',
  'blockchain',
  'big data',
  'machine learning',
  'data science',
  'cloud computing',
  'cybersecurity',
  'IoT',
  '5G',
  'quantum computing',
  'virtual reality',
  'augmented reality',
  'automated systems',
  'natural language processing',
  'robotics',
  'smart devices',
  'digital marketing',
  'e-commerce',
  'fintech',
  'health tech',
  'edtech',
  'supply chain management',
  'logistics',
  'artificial intelligence',
  'deep learning',
  'predictive analytics',
  'edge computing',
  'bioinformatics',
  'digital transformation',
  'enterprise software',
  'internet security',
  'regtech',
  'telemedicine',
  'privacy',
  'machine vision',
  'deepfake detection',
  'generative models',
  'AI ethics',
  'blockchain scalability',
  'smart contracts',
  'cryptocurrency',
  'financial modeling',
  'investment analytics',
  'telecommunications',
  'user experience design',
  'personalization',
  'data mining',
  'software architecture',
  'agile methodologies',
  'strategy',
  'innovation',
  'computer vision',
  'data governance',
  'scalable architecture',
  'risk management',
  'quantum cryptography',
  'behavioral analytics',
  'biometrics',
  'voice recognition',
  'human-computer interaction',
  'immersive technology',
  'network security',
  'enterprise architecture',
  'digital twins',
  'tech ethics',
  'product management',
  'collaborative tools',
  'cyber-physical systems',
  'privacy engineering',
  'social media analytics',
  'virtual assistants',
  'data-driven marketing',
  'cloud-native applications',
  'edge AI',
  'AI-driven automation',
  '5G networks',
  'cloud security',
  'real-time analytics',
  'quantum algorithms',
  'neural networks',
  'data lakes',
  'machine learning operations (MLOps)',
  'devops',
  'data integration',
  'security operations center (SOC)',
];
