module.exports = TOPICS = [
  'Bitcoin',
  'blockchain technology',
  'cryptocurrency markets',
  'decentralized finance (DeFi)',
  'smart contracts',
  'blockchain scalability',
  'cryptographic security',
  'mining operations',
  'wallet security',
  'digital assets',
  'financial technology (fintech)',
  'peer-to-peer networks',
  'tokenomics',
  'blockchain governance',
  'crypto trading strategies',
  'initial coin offerings (ICOs)',
  'non-fungible tokens (NFTs)',
  'stablecoins',
  'decentralized applications (dApps)',
  'cryptocurrency regulations',
  'digital identity on blockchain',
  'cryptocurrency exchanges',
  'cryptocurrency wallets',
  'Ethereum and smart contracts',
  'layer 2 solutions',
  'blockchain interoperability',
  'self-sovereign identity',
  'privacy coins',
  'central bank digital currencies (CBDCs)',
  'cryptocurrency market analysis',
  'blockchain in supply chain management',
  'digital currency adoption',
  'financial inclusion through blockchain',
  'blockchain for social good',
  'energy-efficient mining',
  'blockchain in healthcare',
  'crypto payment systems',
  'tokenization of assets',
  'blockchain in real estate',
  'cross-border payments',
  'cryptocurrency and taxation',
  'crypto investment strategies',
  'cybersecurity in cryptocurrency',
  'regulatory compliance in crypto',
  'stablecoin mechanisms',
  'market volatility in cryptocurrencies',
  'blockchain for transparency',
  'cryptocurrency custody solutions',
  'crypto and NFTs in art',
  'blockchain analytics',
  "blockchain's impact on traditional finance",
  'cryptocurrency volatility management',
  'distributed ledger technology (DLT)',
  'blockchain for voting systems',
  'cryptocurrency forks',
  'digital currencies in developing countries',
  'blockchain for supply chain transparency',
  'financial modeling with cryptocurrencies',
  'cryptocurrency trading platforms',
  'blockchain and data privacy',
  'investment strategies in blockchain',
  'crypto security protocols',
  'decentralized governance models',
  'blockchain in gaming',
  'AI in cryptocurrency trading',
  'metaverse and cryptocurrency integration',
  'blockchain for loyalty programs',
  'decentralized autonomous organizations (DAOs)',
  'NFT marketplaces',
  'crypto-based crowdfunding',
  'blockchain for disaster recovery',
  'cryptocurrency and the gig economy',
  'impact of blockchain on logistics',
  'blockchain-based identity verification',
  'environmental impact of cryptocurrencies',
  'blockchain for intellectual property',
  'future of digital currencies',
];
