#!/bin/bash

cd $HOME
mkdir -p pwr-hca
cd pwr-hca

sudo ufw enable -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 8231/tcp
sudo ufw allow 8085/tcp
sudo ufw allow 7621/udp

sudo apt update && sudo apt upgrade -y
if ! command -v screen &> /dev/null; then
  sudo apt install screen -y
fi

sudo apt install -y openjdk-19-jre-headless

wget https://github.com/pwrlabs/PWR-Validator-Node/raw/main/validator.jar
wget https://github.com/pwrlabs/PWR-Validator-Node/raw/main/config.json

read -p "Enter your desired password: " password

echo $password | sudo tee password

SERVER_IP=$(hostname -I | awk '{print $1}')

sudo java -jar validator.jar password $SERVER_IP --compression-level 0

echo "Please add the following RPC to your Metamask:"
echo "RPC Name: Ethereum+"
echo "RPC URL: https://ethereumplus.pwrlabs.io/"
echo "Chain ID: 10023"
echo "Currency Symbol: ETH"
echo "Explorer URL: https://ethplusexplorer.pwrlabs.io/"
echo ""
echo "Enter the private key generated by the validator into Metamask."
read -p "After you have set up Metamask, press [Enter] to continue..."

screen -S pwr -dm
screen -S pwr -p 0 -X stuff "nohup sudo java -jar validator.jar password $SERVER_IP --compression-level 0 &\n"

echo "Validator node is now running in the background."
echo "Subscribe: https://t.me/HappyCuanAirdrop"
